### ISSUE TITLE
Special characters and alolan-form

### ISSUE THREAD

**Issue by nehemiah-negussie** [nehemiah-negussie/GeorgeBOT#1]
Pokemon like Nidoran♂ or Alolan Geodude tend to have issues because hints are longer than normal. An example would be N__or_n_, where the hint gives one extra space for the special character ♂.

**Comment by therealOri** [comment]
@nehemiah-negussie 
In the push request that I have done recently, This has been fixed with the Nidoran male and female. idk about the alolan geodude as I didn't see anything next to its name. But I can 100% confirm I have fixed this with the emoji's.
