### ISSUE TITLE
question

### ISSUE THREAD

**Issue by lemonxdop** [nehemiah-negussie/GeorgeBOT#3]
Any idea how to use this code in mobile

**Comment by nehemiah-negussie** [comment]
Unfortunately, it's going to be pretty difficult to run this project on mobile as it depends on your phone's OS. On Android there are workarounds like Termux, a Linux environment emulator for Android, which might work but I haven't tested with this code yet. On iOS you can look for other environment emulators and try those. Another viable solution could possibly be repl.it though I'm unsure of how browser based IDEs would work on mobile. These are all just ideas of possibilities you could use to run it.

**Comment by lemonxdop** [comment]
Thanks for giving this info
